### ISSUE TITLE
EEified model error: Dst tensor is not initialized

### ISSUE THREAD

**Issue by giswqs** [gee-community/ee-tensorflow-notebooks#1]
@KMarkert Thank you for this excellent tutorial! I was able to follow through from the beginning until the section **Creating an EEified model** when I ran into an error `Dst tensor is not initialized.` I googled and found that this error likely occurred because the [GPU is out of memory](https://devtalk.nvidia.com/default/topic/1065072/tensorflow-models-gpu-out-of-memory/). However, I am not sure how to resolve this issue. Any advice will be greatly appreciated. 

**Code**
```
# Put the EEified model next to the trained model directory.
EEIFIED_DIR = 'gs://{}/eeified_{}/'.format(BUCKET,MODEL_NAME)
# change to your specific project
# PROJECT = 'ee-sandbox'
PROJECT = '	api-project-141292844612'

# # You need to set the project before using the model prepare command.
!earthengine set_project {PROJECT}
!earthengine --no-use_cloud_api model prepare --source_dir {TF_DIR} --dest_dir {EEIFIED_DIR} --input {input_dict} --output {output_dict}
```

**Output**
```
Running command using Cloud API.  Set --no-use_cloud_api to go back to using the API

Successfully saved project id
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Dst tensor is not initialized.
	 [[{{node RestoreV2}}]]
  (1) Internal: Dst tensor is not initialized.
	 [[{{node RestoreV2}}]]
	 [[GroupCrossDeviceControlEdges_0/StatefulPartitionedCall_2/Identity_212/_438]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/earthengine", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ee/cli/eecli.py", line 92, in main
    tf.app.run(_run_command, argv=sys.argv[:1])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/ee/cli/eecli.py", line 81, in _run_command
    dispatcher.run(args, config)
  File "/usr/local/lib/python3.6/dist-packages/ee/cli/commands.py", line 327, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "/usr/local/lib/python3.6/dist-packages/ee/cli/commands.py", line 327, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "/usr/local/lib/python3.6/dist-packages/ee/cli/commands.py", line 1830, in run
    local_model_dir, tag, in_spec, out_spec, vars_path)
  File "/usr/local/lib/python3.6/dist-packages/ee/cli/commands.py", line 1746, in _make_rpc_friendly
    meta_graph = tf.saved_model.load(sesh, [tag], model_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 423, in load
    self.restore_variables(sess, saver, import_scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 377, in restore_variables
    saver.restore(sess, self._variables_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Dst tensor is not initialized.
	 [[{{node RestoreV2}}]]
  (1) Internal: Dst tensor is not initialized.
	 [[{{node RestoreV2}}]]
	 [[GroupCrossDeviceControlEdges_0/StatefulPartitionedCall_2/Identity_212/_438]]
0 successful operations.
0 derived errors ignored.
```

**Comment by KMarkert** [comment]
@giswqs glad you find it useful! Yes, the GPU runs out of memory...not sure why exactly but my suspicion is that the model is large and there is a lot of data. The workflow gets stuck where you adjust the model to accept EE arrays, could be something with how the EE API does this...

One way I got around this (which is not very clean) is to restart the notebook runtime and pick up at `Creating an EEified model`. When doing this, you don't have to retrain or save the model again but you loose all of the variables from before and is a little annoying to have to do this.

I will look into a cleaner way of doing this maybe by [clearing the graph](https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session) before running `earthengine model prepare` which should free memory.

**Comment by giswqs** [comment]
@KMarkert Thanks a lot for the suggestion! I will try it and let you know how it works.
